services:
  prowlarr:
    image: ghcr.io/hotio/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Budapest
      - UMASK=002
      - PROWLARR_API=${PROWLARR_API}
    volumes:
      - /srv/docker-data/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
networks:
  arr_stack:
    external: true
