services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Budapest
      - DEFAULT_WORKSPACE=/config/workspace
      - PASSWORD=${CODE_SERVER_PASSWORD}
    volumes:
      - /srv/docker-data/code-server:/config
      - /root/homelab:/config/workspace/homelab
    ports:
      - 100.98.146.14:8443:8443
    restart: unless-stopped
