"""Every user-facing string. One language ships; a second is translation."""

S = {
    "app_name": "Pedikűr",
    "login_title": "Bejelentkezés",
    "login_user": "Felhasználónév",
    "login_password": "Jelszó",
    "login_submit": "Belépés",
    "login_failed": "Hibás felhasználónév vagy jelszó.",
    "login_locked": "A fiók ideiglenesen zárolva. Próbáld újra 15 perc múlva.",
    "logout": "Kilépés",
    "nav_today": "Ma",
    "nav_calendar": "Naptár",
    "nav_clients": "Kliensek",
    "nav_more": "Több",
    "nav_label": "Fő navigáció",

    "settings_title": "Beállítások",
    "settings_treatments": "Kezelések és árak",
    "settings_hours": "Munkaidő",
    "save": "Mentés",

    "treatments_title": "Kezelések",
    "treatment_name": "Név",
    "treatment_duration": "Hossz (perc)",
    "treatment_price": "Ár (EUR)",
    "treatment_new": "Új kezelés",
    "treatment_none": "Még nincs egyetlen kezelés sem. Vedd fel az elsőt lent.",
    "minutes_short": "perc",
    "deactivate": "Kivezetés",
    "activate": "Visszaállítás",
    "inactive": "Kivezetve",
    "treatment_name_required": "A névnek nem szabad üresnek lennie.",
    "treatment_price_invalid": "Az ár nem értelmezhető. Például: 25,00",
    "treatment_duration_invalid": "A hossz csak egész perc lehet, legalább 5.",

    "hours_title": "Munkaidő",
    "closed": "Zárva",
    "hours_open": "Nyitás",
    "hours_close": "Zárás",
    "hours_end_before_start": "A zárás nem lehet korábban, mint a nyitás: ",
    "hours_saved": "Munkaidő mentve.",

    "weekdays": ["Hétfő", "Kedd", "Szerda", "Csütörtök",
                 "Péntek", "Szombat", "Vasárnap"],
}
