"""Every user-facing string. One language ships; a second is translation."""

S = {
    "app_name": "Pedikűr",
    "login_title": "Bejelentkezés",
    "login_user": "Felhasználónév",
    "login_password": "Jelszó",
    "login_submit": "Belépés",
    "login_failed": "Hibás felhasználónév vagy jelszó.",
    "login_locked": "A fiók ideiglenesen zárolva. Próbáld újra 15 perc múlva.",
    "logout": "Kilépés",
    "nav_today": "Ma",
    "nav_calendar": "Naptár",
    "nav_clients": "Kliensek",
    "nav_more": "Több",
    "nav_label": "Fő navigáció",

    "settings_title": "Beállítások",
    "settings_treatments": "Kezelések és árak",
    "settings_hours": "Munkaidő",
    "settings_stock": "Készlet",
    "settings_expenses": "Kiadások",
    "save": "Mentés",

    "treatments_title": "Kezelések",
    "treatment_name": "Név",
    "treatment_duration": "Hossz (perc)",
    "treatment_price": "Ár (EUR)",
    "treatment_new": "Új kezelés",
    "treatment_none": "Még nincs egyetlen kezelés sem. Vedd fel az elsőt lent.",
    "minutes_short": "perc",
    "deactivate": "Kivezetés",
    "activate": "Visszaállítás",
    "inactive": "Kivezetve",
    "treatment_name_required": "A névnek nem szabad üresnek lennie.",
    "treatment_price_invalid": "Az ár nem értelmezhető. Például: 25,00",
    "treatment_duration_invalid": "A hossz csak egész perc lehet, legalább 5.",
    "treatment_name_taken": "Már van ilyen nevű kezelés.",

    "new_visit": "Új időpont",
    "client": "Kliens",
    "choose_client": "Válassz klienst",
    "starts_at": "Kezdés",
    "ends_at_optional": "Vége (ha hosszabb a szokásosnál)",
    "slot_taken": "Ez az idősáv már foglalt.",
    "walk_in_no_room": "Ma már nincs szabad idő ehhez a kezeléshez.",
    "visit_needs_treatment": "Válassz legalább egy kezelést.",
    "visit_time_invalid": "A megadott időpont nem értelmezhető.",
    "visit_client_missing": "Ez a kliens már nem foglalható.",
    "visit_treatment_missing": "A választott kezelés már nem létezik.",

    "done": "Kész",
    "more_options": "Továbbiak",
    "findings": "Amit találtam",
    "note": "Amit csináltam",
    "add_treatment": "Kezelés hozzáadása",
    "add": "Hozzáad",
    "cancelled": "Lemondta",
    "no_show": "Nem jött el",
    "price_override": "Ár, ha eltér",
    "visit_gone": "Ez a látogatás már nem létezik.",
    "visit_slot_taken": "Az idősávot közben elfoglalta valaki más.",
    "visit_bad_status": "Ismeretlen állapot.",
    "remove": "Törlés",

    "unclosed_visits": "lezáratlan látogatás",
    "no_visits_today": "Ma nincs bejegyzett látogatás",
    "walk_in": "Beeső kliens",
    "start": "Indítás",

    "search": "Keresés",
    "new_client": "Új kliens",
    "client_name": "Név",
    "client_phone": "Telefon",
    "client_email": "E-mail",
    "client_address": "Cím",
    "client_notes": "Megjegyzés",
    "alert_label": "Figyelmeztetés",
    "alert_hint": "cukorbetegség, véralvadásgátló, allergia",
    "has_alert": "Figyelmeztetés",
    "history": "Előzmény",
    "no_history": "Még nincs lezárt látogatás",
    "no_results": "Nincs találat",
    "client_name_required": "A kliensnek kell egy név.",
    "archive": "Archiválás",
    "unarchive": "Visszahozás",
    "archived": "Archiválva",
    "archive_hint": "Eltűnik a listákból, minden adata megmarad.",
    "show_archived": "Archiváltak is",

    "expenses_title": "Kiadások",
    "expense_none": "Még nincs kiadás",
    "expense_new": "Új kiadás",
    "expense_date": "Dátum",
    "expense_vendor": "Hol",
    "expense_amount": "Összeg",
    "expense_category": "Mire",
    "expense_note": "Megjegyzés",
    "expense_line": "Ami bejött a készletbe",
    "expense_line_hint": "Csak ha árut vettél. Enélkül is jó a kiadás.",
    "expense_line_product": "Termék",
    "expense_line_qty": "Mennyiség",
    "expense_line_cost": "Egységár",
    "expense_line_diff": "Tételek eltérnek",
    "expense_date_invalid": "A dátum nem jó, éééé-hh-nn kell.",
    "expense_amount_invalid": "Az összeg nem szám.",
    "expense_category_invalid": "Ilyen kategória nincs.",
    "expense_line_invalid": "A tételsor nem jó, ezért semmit nem mentettem el.",
    "category_anyag": "Anyag",
    "category_eszkoz": "Eszköz",
    "category_berleti_dij": "Bérleti díj",
    "category_rezsi": "Rezsi",
    "category_marketing": "Marketing",
    "category_egyeb": "Egyéb",

    "stock_title": "Készlet",
    "stock_none": "Még nincs termék",
    "stock_new": "Új termék",
    "product_name": "Név",
    "product_unit": "Egység",
    "product_unit_hint": "flakon, tekercs, doboz, pár, db",
    "product_min_stock": "Minimum készlet",
    "product_sale_price": "Eladási ár, ha árulja is",
    "opening_qty": "Nyitókészlet",
    "opening_cost": "Egységár",
    "stock_low": "Kevés",
    "stock_no_price": "Nincs ára",
    "stock_movement": "Mozgás",
    "stock_qty": "Mennyiség",
    "stock_reason": "Mi történt",
    "stock_reason_opening": "Nyitókészlet",
    "stock_reason_correction": "Korrekció",
    "stock_reason_waste": "Selejt",
    "stock_reason_purchase": "Beszerzés",
    "stock_reason_consumption": "Felhasználás",
    "stock_reason_sale": "Eladás",
    "stock_qty_invalid": "A mennyiség nem szám.",
    "stock_qty_zero": "A nulla nem mozgás.",
    "stock_cost_invalid": "Az egységár nem jó.",
    "stock_reason_invalid": "Ezt a mozgást nem lehet kézzel felvenni.",
    "product_name_required": "A terméknek kell egy név.",
    "product_unit_required": "A terméknek kell egy egység.",
    "show_archived_products": "Archiváltak is",
    "hide_archived_products": "Csak az aktívak",

    "add_product": "Termék hozzáadása",
    "product_qty": "Mennyiség",
    "visit_product_invalid": "Ezt a terméket nem lehet hozzáadni.",
    "visit_total": "Összesen",

    "recipe_title": "Recept",
    "recipe": "Recept",
    "recipe_none": "Nincs hozzá anyag",
    "recipe_product": "Anyag",
    "recipe_yield": "Hány kezelésre elég egy egység",
    "recipe_treatments": "kezelés",
    "recipe_yield_hint": "egy flakon kb. 30 töltés",
    "recipe_yield_invalid": "A szám nem jó: egy egységnek legalább egy töredék kezelésre elegendőnek kell lennie.",
    "recipe_no_products": "Előbb vegyél fel terméket a Készlet alatt.",
    "recipe_partial_hint": "Csak a drága anyagokhoz kell. Ami nincs itt, arra nem számol fedezetet.",

    "hours_title": "Munkaidő",
    "closed": "Zárva",
    "hours_open": "Nyitás",
    "hours_close": "Zárás",
    "hours_end_before_start": "A zárás nem lehet korábban, mint a nyitás: ",
    "hours_saved": "Munkaidő mentve.",
    "hours_time_invalid": "Az idő formátuma nem jó, ",

    "weekdays": ["Hétfő", "Kedd", "Szerda", "Csütörtök",
                 "Péntek", "Szombat", "Vasárnap"],
    # strftime("%a") answers "Mon" in a C-locale container, not "Hét"
    "weekdays_short": ["H", "K", "Sze", "Cs", "P", "Szo", "V"],
    "book_here": "Foglalás ide",
    "week_prev": "Előző hét",
    "week_next": "Következő hét",
    "week_today": "Ma",
    "closed_day": "Zárva",
}
