---
- Quick Links:
    - GitHub Homelab:
        - icon: github-light.png
          href: https://github.com/Pironex9/homelab
    - Tailscale:
        - icon: tailscale.png
          href: https://login.tailscale.com/admin/machines
    - Hetzner:
        - icon: hetzner.png
          href: https://console.hetzner.com/projects/13016027/dashboard
    - Cloudflare:
        - icon: cloudflare.png
          href: https://dash.cloudflare.com/47bd0954876ebc191ce6b29e6ba0df65/home/domains
    - Resend:
        - icon: si-resend-#ffffff
          href: https://app.resend.com
    - r/selfhosted:
        - icon: reddit.png
          href: https://www.reddit.com/r/selfhosted
    - Docs:
        - icon: mkdocs.png
          href: https://docs.homelabor.net
    - LinkedIn:
        - icon: linkedin.png
          href: https://www.linkedin.com/in/norbert-csicsay-497195334
    - Lessons:
        - icon: mdi-school-outline
          href: http://192.168.0.204:8800/lessons/
